- name: Create CephFS data pool
  command: "microceph.ceph osd pool create {{ cephfs_data_pool }} {{ cephfs_pg_num }}"
  register: create_data_pool
  changed_when: "'pool' in create_data_pool.stdout and 'created' in create_data_pool.stdout"
  failed_when:
    - create_data_pool.rc != 0
    - "'already exists' not in create_data_pool.stderr"

- name: Create CephFS metadata pool
  command: "microceph.ceph osd pool create {{ cephfs_metadata_pool }} {{ cephfs_pg_num }}"
  register: create_metadata_pool
  changed_when: "'pool' in create_metadata_pool.stdout and 'created' in create_metadata_pool.stdout"
  failed_when:
    - create_metadata_pool.rc != 0
    - "'already exists' not in create_metadata_pool.stderr"

- name: Create CephFS filesystem
  command: "microceph.ceph fs new {{ cephfs_name }} {{ cephfs_metadata_pool }} {{ cephfs_data_pool }}"
  register: create_fs
  changed_when: "'created' in create_fs.stdout"
  failed_when:
    - create_fs.rc != 0
    - "'already exists' not in create_fs.stderr"

- name: Get admin key
  command: microceph.ceph auth get-key client.admin
  register: admin_key
  changed_when: false

- name: Save admin key as fact
  set_fact:
    ceph_admin_key: "{{ admin_key.stdout }}"
