# Ce role initialize le mode cluster de Docker (swarm)
---
- name: Check if Docker Swarm is already initialized
  command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
  register: swarm_state
  changed_when: false

- name: Initialize Docker Swarm
  docker_swarm:
    state: present
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: swarm_init
  when: swarm_state.stdout != "active"


- name: Get manager join token
  command: docker swarm join-token -q manager
  register: manager_token
  changed_when: false

- name: Get worker join token
  command: docker swarm join-token -q worker
  register: worker_token
  changed_when: false

- name: Set facts for swarm info
  set_fact:
    manager_token: "{{ manager_token.stdout }}"
    worker_token: "{{ worker_token.stdout }}"
    manager_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
