# Ce role autorise certaines fonctionnalités Apparmor
---
- name: Find snap-confine profile file
  find:
    paths: /var/lib/snapd/apparmor/profiles/
    patterns: "snap-confine.snapd.*"
  register: snap_confine_file

- name: Display found snap-confine file
  debug:
    var: snap_confine_file.files[0].path
  when: snap_confine_file.matched > 0

- name: Check if capabilities are already in the file
  shell: |
    grep -q "capability net_admin," {{ snap_confine_file.files[0].path }} || echo "missing_net_admin"
    grep -q "capability perfmon," {{ snap_confine_file.files[0].path }} || echo "missing_perfmon"
  args:
    executable: /bin/bash
  register: capability_check
  changed_when: capability_check.stdout | length > 0
  failed_when: false
  when: snap_confine_file.matched > 0

- name: Add lines and reload apparmor
  when: "snap_confine_file.matched > 0 and ('missing_net_admin' in capability_check.stdout or 'missing_perfmon' in capability_check.stdout)"
  block:
    - name: Insert net_admin capability after dac_override
      lineinfile:
        path: "{{ snap_confine_file.files[0].path }}"
        line: "    capability net_admin,"
        insertafter: "capability dac_override,"
        state: present
      when: "'missing_net_admin' in capability_check.stdout"
      register: net_admin_added

    - name: Insert perfmon capability after net_admin
      lineinfile:
        path: "{{ snap_confine_file.files[0].path }}"
        line: "    capability perfmon,"
        insertafter: "capability net_admin,"
        state: present
      when: "'missing_perfmon' in capability_check.stdout"
      register: perfmon_added

    - name: Restart AppArmor service if changes were made
      service:
        name: apparmor
        state: restarted
      when: (net_admin_added is defined and net_admin_added.changed) or
            (perfmon_added is defined and perfmon_added.changed)

    - name: Reload AppArmor profiles
      shell: apparmor_parser -r /var/lib/snapd/apparmor/profiles/snap-confine.snapd.*
      args:
        executable: /bin/bash
      changed_when: false
