- name: Check GRUB_CMDLINE_LINUX_DEFAULT
  shell: grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub || true
  register: grub_cmdline
  changed_when: false

- name: Backup grub if it is by default
  copy:
    src: /etc/default/grub
    dest: /etc/default/grub.bak
    remote_src: true
    mode: '0744'
  when: grub_cmdline.stdout == 'GRUB_CMDLINE_LINUX_DEFAULT="quiet"'

- name: Disable AppArmor in GRUB_CMDLINE_LINUX_DEFAULT if needed
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: "{{ grub_cmdline.stdout | regex_replace('apparmor=0', '') | regex_replace('\"$', ' apparmor=0\"') }}"
    backrefs: false
  when: "'apparmor=0' not in grub_cmdline.stdout"
  register: grub_modified

- name: Update grub if needed
  command: update-grub
  when: grub_modified.changed

- name: Reboot if needed
  reboot:
    msg: "Redémarrage pour désactiver AppArmor"
    pre_reboot_delay: 5
  when: grub_modified.changed
