---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - apparmor
      - binutils
      - busybox
      - cpio
      - cron
      - dash
      - discover
      - git
      - dmidecode
      - gnupg
      - less
      - libxml2
      - nano
      - patch
      - perl
      - procps
      - sudo
      - tar
      - traceroute
      - unzip
      - util-linux
      - wget
    state: present
  register: apt_result
  retries: 5
  delay: 30
  until: apt_result is succeeded

- name: Remove the package if installed
  ansible.builtin.apt:
    name: 
      - snapd
    state: absent

- name: Fail if installation was unsuccessful
  fail:
    msg: "Packages failed to install after multiple retries."
  when: apt_result is failed
