---
- name: Add user without password
  become: true
  block:
    - name: Create ansible_user without a password
      user:
        name: ansible_user
        shell: /bin/bash
        createhome: true
        password: ''

    - name: Ensure ansible_user has sudo privileges
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible_user'
        line: 'ansible_user ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'
