# Ce role configure la liaison ssh et l'utilisateur ansible qui va être utilisé pour éxecuter des playbooks ansible
---
- name: Create a the admin user with sudo privileges
  user:
    name: "{{ admin_user }}"
    state: present
    groups: sudo
    append: true
    create_home: true
    shell: /bin/bash

- name: Ensure SSH key directory exists
  file:
    path: "/home/{{ admin_user }}/.ssh"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0700'

- name: Add authorized public key
  copy:
    content: "{{ ssh_pubkey }}"
    dest: "/home/{{ admin_user }}/.ssh/authorized_keys"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0600'

# - name: Setup passwordless sudo
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: '^%sudo'
#     line: '%sudo ALL=(ALL) NOPASSWD: ALL'
#     validate: '/usr/sbin/visudo -cf %s'
#   notify: Restart ssh


# - name: Restart SSH to apply changes
#   service:
#     name: ssh
#     state: restarted
