# Ce rôle configure le serveur NTP de AGO sur les noeuds et synchronise l'heure
# Ce rôle est a lancer dans le cas ou l'heure des noeuds n'est pas synchronisée
---
- name: Configure NTP servers
  ansible.builtin.lineinfile:
    dest: /etc/systemd/timesyncd.conf
    line: 'NTP=srv-ad-01.aero44.local'
    create: true
    mode: '0644'
  notify: Restart systemd-timesyncd


- name: Restart NTP configuration and set timezone
  become: true
  block:
    - name: Set time zone to Europe/Paris
      ansible.builtin.command: timedatectl set-timezone Europe/Paris
      changed_when: true

    - name: Disable NTP temporarily
      ansible.builtin.command: timedatectl set-ntp false
      changed_when: false

    - name: Re-enable NTP
      ansible.builtin.command: timedatectl set-ntp true
      changed_when: false
      notify: Restart systemd-timesyncd