- name: Ensure Docker is started and enabled
  service:
    name: docker
    state: started
    enabled: true

- name: Ensure User is in Docker group
  user:
    name: "{{ admin_user }}"
    groups: docker
    append: true

# - name: Reset SSH connection to apply new group
#   meta: reset_connection
