- name: Check if Docker Swarm is already initialized
  command: docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'
  register: swarm_state
  changed_when: false

- name: Join swarm as a worker
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars[groups['swarm_managers'][0]]['worker_token'] }}"
    remote_addrs: ["{{ hostvars[groups['swarm_managers'][0]]['manager_ip'] }}:2377"]
  when: swarm_info.swarm.LocalNodeState is not defined or swarm_info.swarm.LocalNodeState != "active"
