- name: Get swarm nodes
  docker_node_info:
  register: node_info

- name: Count manager and worker nodes
  set_fact:
    manager_count: "{{ node_info.nodes | selectattr('Spec.Role', 'equalto', 'manager') | list | length }}"
    worker_count: "{{ node_info.nodes | selectattr('Spec.Role', 'equalto', 'worker') | list | length }}"

- name: Show concise swarm status
  debug:
    msg: >-
      Docker Swarm is up with {{ manager_count }} manager(s) and {{ worker_count }} worker(s).
