---
- name: Setup SSH link and Ansible user
  hosts: [swarm]
  become: true
  become_user: root
  vars:
    # insérer une clef publique ssh
    ssh_pubkey: ""

  tasks:
    - name: Create a the admin user with sudo privileges
      user:
        name: "{{ admin_user }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        shell: /bin/bash

    - name: Ensure SSH key directory exists
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0700'

    - name: Add authorized public key
      copy:
        content: "{{ ssh_pubkey }}"
        dest: "/home/{{ admin_user }}/.ssh/authorized_keys"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0600'