# Ce playbook déploie portainer en Haute disponibilité sur un cluster
# Il déploie un agent portainer sur chaque noeud de la swarm et l'interface portainer sur un noeud de la swarm
# Ce role est a lancer seulement après avoir installé docker et docker compose, initialisé la swarm et configuré microceph
- name: Deploy Portainer and Agent services
  hosts: [swarm]
  become: true
  vars:
    network_name: portainer
    share_name: portainer
  roles:
    - docker-stack-portainer
