---
- name: Collect Docker ps and stats from hosts
  hosts: swarm
  become: true
  gather_facts: false
  tasks:
    - name: Run 'docker ps'
      ansible.builtin.command: docker ps
      register: docker_ps_output
      changed_when: false

    - name: Run 'docker stats --no-stream'
      ansible.builtin.command: docker stats --no-stream
      register: docker_stats_output
      changed_when: false

    - name: Display Docker PS Output
      ansible.builtin.debug:
        var: docker_ps_output.stdout_lines

    - name: Display Docker Stats Output
      ansible.builtin.debug:
        var: docker_stats_output.stdout_lines
