---
- name: Prepare nodes for Microceph
  hosts: [swarm]
  become: true
  roles:
    - role: common-packages-install
    - role: microceph-install

- name: Bootstrap Microceph cluster on primary node
  hosts: [swarm]
  become: true
  roles:
    - role: microceph-cluster-init


- name: Configure Microceph disks on all nodes
  hosts: [swarm]
  become: true
  roles:
    - role: microceph-disk-setup-auto
    # - role: microceph-disk-setup-manual


- name: Initialize CephFS on primary node
  hosts: swarm[0]
  become: true
  roles:
    - role: microceph-cephfs-setup

- name: Configure CephFS mount points on all nodes
  hosts: [swarm]
  become: true
  roles:
    - role: microceph-cephfs-mount
