---
- name: Prepare nodes
  hosts: [swarm]
  become: true
  roles:
    - role: ntp-setup-sync
    - role: common-packages-install
    # - role: apparmor-disable

# - name: Install Microceph
#   hosts: [swarm]
#   become: true
#   roles:
#     - role: microceph-install

# - name: Setup Apparmor for Microceph
#   hosts: [swarm]
#   become: true
#   roles:
#     - role: apparmor-setup

# - name: Bootstrap MicroCeph cluster on primary node
#   hosts: [swarm]
#   become: true
#   roles:
#     - role: microceph-cluster-init


# - name: Configure MicroCeph disks on all nodes
#   hosts: [swarm]
#   become: true
#   roles:
# # ONLY USE ONE OR THE OTHER
#     - role: microceph-disk-setup-auto
    # - role: microceph-disk-setup-manual


# - name: Initialize CephFS on primary node
#   hosts: swarm[0]
#   become: true
#   roles:
#     - role: microceph-cephfs-setup

# - name: Configure CephFS mount points on all nodes
#   hosts: [swarm]
#   become: true
#   roles:
#     - role: microceph-cephfs-mount

- name: Install Docker and add docker user to docker group
  hosts: [swarm]
  become: true
  vars:
    docker_architecture: "{{ lookup('pipe', 'dpkg --print-architecture') }}"
    docker_codename: "{{ ansible_facts['distribution_release'] }}"
  roles:
    - docker-setup

- name: Initialize Docker Swarm
  hosts: [swarm]
  become: true
  roles:
    - role: swarm-init

- name: Initialize the first manager
  hosts: swarm[0]
  become: true
  roles:
    - role: swarm-init-manager

- name: Join additional managers to the swarm
  hosts: swarm[1:]
  become: true
  roles:
    - role: swarm-managers-join

# - name: Join workers to the swarm
#   hosts: swarm_workers
#   become: true
#   roles:
#     - role: swarm-workers-join

- name: Verify swarm setup
  hosts: [swarm]
  # hosts: swarm_managers[0]
  become: true
  roles:
    - role: swarm-verify

- name: Deploy Portainer and Agent services
  hosts: [swarm]
  become: true
  vars:
    network_name: portainer
    share_name: portainer
  roles:
    - docker-stack-portainer
