---
- name: Get all MicroCeph node IP addresses
  set_fact:
    ceph_monitor_ips: "{{ groups['swarm'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"

- name: Create CephFS mount directory
  file:
    path: "{{ cephfs_mount_point }}"
    state: directory
    mode: '0755'

- name: Add CephFS to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ ceph_monitor_ips | map('regex_replace', '^(.*)$', '\\1:6789') |
     join(',') }}:/ {{ cephfs_mount_point }} ceph name=admin,secret={{ hostvars[groups['swarm'][0]].ceph_admin_key }},_netdev 0 0"
    regexp: "^.*{{ cephfs_mount_point }} ceph.*$"


# - name: Apply mount configuration
#   command: mount -a
#   changed_when: false
#   ignore_errors: true

# - name: Display ceph mount point
#   debug:
#     msg: "{{ cephfs_mount_point }}"

- name: Ensure CephFS is mounted
  ansible.posix.mount:
    path: "{{ cephfs_mount_point }}"
    src: "{{ ceph_monitor_ips | map('regex_replace', '^(.*)$', '\\1:6789') | join(',') }}:/"
    fstype: ceph
    opts: "name=admin,secret={{ hostvars[groups['swarm'][0]].ceph_admin_key }},_netdev"
    state: mounted

- name: Reload systemd daemon
  systemd:
    daemon_reload: true
  changed_when: false
