---
name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Lint Ansible YAML files
        run: |
          yamllint . --exclude .github
          ansible-lint

    # - name: Syntax check playbooks
    #   run: |
    #     ansible-playbook playbooks/site.yml --syntax-check -i inventory/local
